### ISSUE TITLE
Tilføj Galleri (meta)

### ISSUE THREAD

**Issue by neic** [TK-IT/web#4]
- [x] Upload interface
- [x] #10 Lightbox alternativ
- [x] Overvej hvor små/store thumbs skal være - jeg foreslår 6 thunbs/row på pc, 4 på tablet-ish, 3 på mobil.
- [x] Centrer billedet på enkeltbillede-siden #36 
- [x] Maximér størrelsen af enkeltbillede uden at nødvendiggøre scroll. #36 
- [x] Fjern margins/padding på billede på mobilskærme.
- [x] Tilføj link til download af originalbilledet, da det nu ikke længere er trivielt at gætte url'en selv.
- [x] Skjul dato for albums, hvor vi ikke er sikre på arrangementsdatoen (det skal helst være korrekt, når vi viser sådan nogle ting på hjemmesiden)
- [x] Benyt samme opløsninger på thumbs rundt omkring, så vi undgår at skulle generere alt for mange forskellige - men næsten ens - skaleringer. Løses måske med #33 
- [x] Fix swipe #44
- [x] Tilpas URL'en i galleriet til at afspejle hvilket gfår, der er vist. Se #21
- [x] Kun load de billeder vi skal bruge #35 
- [x] Andre filtyper #34 
- [x] Stop afspilning af lyd og video #45

**Comment by furt11** [comment]
Der mangler finpudsninger af html'en og bootstrap-classes, men funktionaliteten er næsten færdig.

**Comment by furt11** [comment]
Nogle småting, der nok bør fikses i galleriet: 
[ ] Overvej hvor små/store thumbs skal være - jeg foreslår 6 thunbs/row på pc, 4 på tablet-ish, 3 på mobil.
[ ] Centrer billedet på enkeltbillede-siden
[ ] Maximér størrelsen af enkeltbillede uden at nødvendiggøre scroll. 
[ ] Fjern margins/padding på billede på mobilskærme.
[ ] Tilføj link til download af originalbilledet, da det nu ikke længere er trivielt at gætte url'en selv.
[ ] Skjul dato for albums, hvor vi ikke er sikre på arrangementsdatoen (det skal helst være korrekt, når vi viser sådan nogle ting på hjemmesiden)
[ ] Benyt samme opløsninger på thumbs rundt omkring, så vi undgår at skulle generere alt for mange forskellige - men næsten ens - skaleringer. 
[ ] Test swipe på IOS-dimser og tilfældige android-dingenoter.
