### ISSUE TITLE
Deployment checklist

### ISSUE THREAD

**Issue by neic** [TK-IT/web#53]
- [x] Database server
- [x] Fix `setting/prod.py`
- [x] cron job til kalender
- [x] Review af settings og unix permissions
- [x] Commit ændringer der er lavet på prod serveren
- [x] Importer flatpages
- [x] Importer billeder
  - [x] Kør script (Venter på #56)
  - [x] Tjek loggen
- [x] Importer et prøve dump af persondata (Venter på #73)
- [x] Fiks alle issues i [Milestone v1.0 beta](https://github.com/TK-IT/web/milestone/1)

_Alt efter beta perioden er flyttet til #74._

**Comment by neic** [comment]
```sh
git pull
pip install --update -r requirements.txt
python3 manage.py migrate --settings=tkweb.settings.prod
python3 manage.py collectstatic --settings=tkweb.settings.prod
```
