### ISSUE TITLE
Persondatabase meta

### ISSUE THREAD

**Issue by neic** [TK-IT/web#61]
Vi vil gerne ændre i persondatabasen fra Django frem for den gamle php-side. For at det kan lade sig gøre skal følgende ske:  
- [x] Lave en model fra den gamle database,  
- [x] rydde op i modellen #63, 
- [x] lave et HTML interface (måske Django admin), 
- [ ] ændre mailsystemet til følge den nye model,

**Comment by neic** [comment]
@Mortal har lavet noget på både [idm](https://github.com/TK-IT/web/tree/idm) og [legacydb](https://github.com/TK-IT/web/tree/legacydb) branchen. Hvorfor er der to?

**Comment by Mortal** [comment]
idm branchen er den rette at bruge. Jeg har også for nylig arbejdet på en model i j60adm-repositoriet, men det er nok ikke så anvendeligt her.

**Comment by Mortal** [comment]
Jeg har rebaset `idm` til `master` (og fikset `tk_prefix`-funktionen i den branch så den håndterer K-præfikser rigtigt).

Min model følger den gamle tabelstruktur tæt; det eneste datamigrering der sker er at tabellerne gradgruppemedlemmer og gruppemedlemmer ikke har PK på den gamle hjemmeside og derfor skal kopieres over i en ny tabel med PK.

På denne måde kan vi vente med at ændre mailsystemets forward-logik indtil efter vi har deployet det nye Django-administrations site til emailadresser og grupper.

**Comment by Mortal** [comment]
Jeg har [tweaket idm/admin.py](https://github.com/TK-IT/web/blob/584e69994a4ddb8aa23c52b67698434fd3d08750/idm/admin.py), så nu kan det alt hvad den gamle side kunne (bortset fra at sende emails):

* Alt er på dansk
* Personlisten:
   * Sorteret alfabetisk på navn
   * Viser titler, emailadresse (som mailto-link), om personen er på hængerlisten og om personen modtager titel-emails
   * Kan filtrere på "Hængerlisten", "Modtager titel-emails", "Afdød" (alle ja/nej)
   * Søgefelt der søger blandt personnavne og emailadresser
   * Viser 100 personer af gangen
* Titellisten:
   * Sorteret efter præfiks og derefter BEST/EFU/FU og derefter alfabetisk på titlen
   * Viser personnavn (med link til personredigering) og "Årgang" (kombination af prefix, period og kind, på formen "BBEST 2013/14" eller "OFU 2012/13")
   * Kan filtrere på BEST/EFU/FU
   * Kan filtrere på CERM/FORM/.../VC/FUAN/EFUIT/TVC/"BEST"
   * Kan filtrere på årgang/præfiks (liste over valgmuligheder på formen "T²OBEST/FU 2010/11")
   * Søgefelt der søger blandt personnavne
   * Viser 100 titler af gangen
* Gruppelisten:
   * Viser navn, regulært udtryk, eksempler
   * Sorteret efter navn

Jeg vil mene at denne adminside er god nok til første release.

**Comment by Mortal** [comment]
Øh... Da jeg trykkede på en checkbox i issue-beskrivelsen, blev teksten erstattet med #63-teksten. :-(

**Comment by neic** [comment]
REST-APIet er udskudt til fremtiden og resten er flyttet til #53 og #74.
